# Generated by Django 3.2.7 on 2021-09-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BRMapp', '0002_brmuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('phone', models.IntegerField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('intro', models.TextField(default='')),
                ('wanted', models.IntegerField(max_length=100)),
                ('passed', models.IntegerField(default=0)),
            ],
        ),
    ]
