# Generated by Django 3.2.7 on 2021-09-20 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BRMapp', '0003_applier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applier',
            old_name='wanted',
            new_name='expect',
        ),
    ]
